name: Workflow which handles PR and workflow dispatch trigger.
on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      label_input:
        description: label value as input.
        type: choice
        required: true
        options:
          - bug
          - duplicate
          - enhancement
      downstream_trigger:
        description: Workflow from which the build is triggered.
        type: string
        required: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: steps.pr-trigger.outputs.lables
    steps:
      - name: Set for PR trigger..
        run: echo "lables=${{ toJSON(github.event.pull_request.labels) }}" >> $GITHUB_OUTPUT
        if: ${{ github.event_name == 'pull_request' }}
        id: pr-trigger
      - name: Set for workflow trigger.
        run: echo "lables=${{format('[{0}]', inputs.label_input)}}" >> $GITHUB_OUTPUT
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: workflow-trigger

  use-matrix:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        loc_labels: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    steps:
      - name: Print each value.
        run: echo "${{ matrix.loc_labels }}"